theme: minima

collections:
    features:
        output: true
        permalink: /features/:path/


defaults:
    - scope:
        path: ""
        type: features
      values:
        layout: feature
