incremental: bool

# theme: minima

baseurl: /text-fabric-data

collections:
    features:
        output: true

defaults:
    - scope:
        path: ""
        type: features
      values:
        layout: page
    - scope:
        path: ""
        type: pages
      values:
        layout: page
    - scope:
        path: "_features/hebrew"
      values:
        lang: hebrew
        feat: true
    - scope:
        path: "_features/greek"
      values:
        lang: greek
        feat: true
